apiVersion: v1
kind: Service
metadata:
  name: projet-nodejs-service
  labels:
    app: projet-nodejs
spec:
  selector:
    app: projet-nodejs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: projet-nodejs-internal
  labels:
    app: projet-nodejs
spec:
  selector:
    app: projet-nodejs
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP